blank_issues_enabled: true
contact_links:
  - name: UNICORN Devs Chat
    url: https://t.me/unicorndevs
    about: Chat with the community about the lucit-backtesting and ask general questions.
  - name: lucit-backtesting Discussions
    url: https://github.com/LUCIT-Systems-and-Development/lucit-backtesting/discussions
    about: Ask general questions.
  - name: lucit-backtesting documentation
    url: https://lucit-backtesting.docs.lucit.tech/
    about: The complete lucit-backtesting documentation.
  - name: Get Professional and Fast Support
    url: https://www.lucit.tech/get-support.html
    about: Contact the LUCIT Development Team.
